services: 
   mongo:
     image: mongo
     restart: always
     environment: 
       MONGO_INITDB_ROOT_USERNAME: asyahir
       MONGO_INITDB_ROOT_PASSWORD: password
     ports:
       - "27017:27017"
     volumes: 
       - mongo-data:/data/db

volumes: 
    mongo-data:
